version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_DATABASE_USER_NAME}
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  volumes:
    - mysql_data:/var/lib/mysql
  ports:
    - "3306:3306"

  redis:
    image: redis:7
  
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn hiringdogbackend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./git-source:/app/git-source
      - ./docker/entrypoint.sh:/entrypoint.sh
      - ./git-source/requirements.txt:/app/requirements.txt
    env_file:
      - ./git-source/.env
    depends_on:
      - db
      - redis
      - rabbitmq
    ports:
      - "8000:8000"

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A hiringdogbackend worker --loglevel=info
    volumes:
      - ./git-source:/app/git-source
      - ./docker/entrypoint.sh:/entrypoint.sh
      - ./git-source/requirements.txt:/app/requirements.txt
    env_file:
      - ./git-source/.env
    depends_on:
      - db
      - redis
      - rabbitmq

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A hiringdogbackend beat --loglevel=info
    volumes:
      - ./git-source:/app/git-source
      - ./docker/entrypoint.sh:/entrypoint.sh
      - ./git-source/requirements.txt:/app/requirements.txt
    env_file:
      - ./git-source/.env
    depends_on:
      - db
      - redis
      - rabbitmq


volumes:
  mysql_data:
