# Generated by Django 5.1.2 on 2025-05-29 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_user_email_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackAndImprovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=False)),
                ('context', models.TextField(blank=True, help_text='Context of the feedback or area of improvement.')),
                ('screenshot', models.ImageField(blank=True, help_text='Screenshot of the area of improvement.', null=True, upload_to='application_feedback')),
                ('feedback_type', models.CharField(blank=True, choices=[('BUG', 'Bug'), ('ENHANCEMENT', 'Enhancement')], max_length=15, null=True)),
                ('priority', models.CharField(blank=True, choices=[('P0', 'High'), ('P1', 'Medium'), ('P2', 'Low')], help_text='Priority of the feedback or improvement.', max_length=15, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_and_improvements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
