# Generated by Django 5.1.2 on 2025-06-05 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_feedbackandimprovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackandimprovement',
            name='is_fixed',
            field=models.BooleanField(default=False),
        ),
    ]
