# Generated by Django 5.1.2 on 2025-05-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0092_job_recommended_score_department_job_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='reason_for_dropping',
            field=models.CharField(blank=True, choices=[('CNI', 'Candidate Not Interested'), ('CNA', 'Candidate Not Available'), ('CNR', 'Candidate Not Responded'), ('OTH', 'Others'), ('RJD', 'Rejected By HDIP'), ('NJ', 'Not Joined Candidate')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='internalinterviewer',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='interviewer_cvs'),
        ),
    ]
