# Generated by Django 5.1.2 on 2025-05-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0094_candidatetointerviewerfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuser',
            name='last_invitation_notification_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
