# Generated by Django 5.1.2 on 2025-05-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0095_clientuser_last_invitation_notification_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidatetointerviewerfeedback",
            name="is_expired",
            field=models.TextField(default=False),
        ),
    ]
