# Generated by Django 5.1.2 on 2025-05-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0097_job_max_exp_job_min_exp'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
