# Generated by Django 5.1.2 on 2025-05-25 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0098_candidate_scheduled_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='crafter_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
