# Generated by Django 5.1.2 on 2025-05-28 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0099_job_crafter_response"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="interview",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="interview",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SCH", "Scheduled"),
                    ("CSCH", "Compete Scheduled"),
                    ("NSCH", "Not Scheduled"),
                    ("RESCH", "Rescheduled"),
                    ("NJ", "Not Joined"),
                    ("PENDING_EVAL", "Pending Evaluation"),
                    ("COMPLETED", "Completed"),
                    ("HREC", "Highly Recommended"),
                    ("REC", "Recommended"),
                    ("NREC", "Not Recommended"),
                    ("SNREC", "Strongly Not Recommended"),
                ],
                db_index=True,
                help_text="Interview status",
                max_length=15,
            ),
        ),
        migrations.AddIndex(
            model_name="interview",
            index=models.Index(
                fields=["interviewer", "scheduled_time", "status"],
                name="dashboard_i_intervi_71f40d_idx",
            ),
        ),
    ]
