# Generated by Django 5.1.2 on 2025-05-28 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0100_alter_interview_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='crafter_response',
        ),
    ]
