# Generated by Django 5.1.2 on 2025-05-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0101_remove_job_crafter_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalinterviewer',
            name='is_bank_account_updated',
            field=models.BooleanField(default=False),
        ),
    ]
