# Generated by Django 5.1.2 on 2025-05-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0103_alter_job_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='billpayments',
            name='amount_received',
            field=models.DecimalField(decimal_places=2, default=0, help_text='The total amount received including any applicable taxes', max_digits=10),
        ),
        migrations.AlterField(
            model_name='billpayments',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='The original amount of the bill without any taxes or adjustments', max_digits=10),
        ),
    ]
