# Generated by Django 5.1.2 on 2025-05-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0104_billpayments_amount_received'),
        ('organizations', '0006_alter_organization_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinglog',
            name='status',
            field=models.CharField(choices=[('PED', 'Pending'), ('PAI', 'Paid')], db_index=True, default='PED', max_length=15),
        ),
        migrations.AddField(
            model_name='billpayments',
            name='billing_logs',
            field=models.ManyToManyField(to='dashboard.billinglog'),
        ),
        migrations.AddIndex(
            model_name='billinglog',
            index=models.Index(fields=['billing_month', 'status'], name='dashboard_b_billing_0f7d2e_idx'),
        ),
    ]
