# Generated by Django 5.1.2 on 2025-05-31 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0105_billinglog_status_billpayments_billing_logs_and_more'),
        ('organizations', '0006_alter_organization_slug'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='billinglog',
            name='dashboard_b_billing_0f7d2e_idx',
        ),
        migrations.AddIndex(
            model_name='billinglog',
            index=models.Index(fields=['client', 'billing_month', 'status'], name='client_billing_status_idx'),
        ),
        migrations.AddIndex(
            model_name='billinglog',
            index=models.Index(fields=['interviewer', 'billing_month', 'status'], name='interviewer_billing_status_idx'),
        ),
    ]
