# Generated by Django 5.1.2 on 2025-06-01 04:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0106_remove_billinglog_dashboard_b_billing_0f7d2e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalclient',
            name='initial_free_interviews_allocation',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
