# Generated by Django 5.1.2 on 2025-06-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0107_internalclient_initial_free_interviews_allocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinglog',
            name='status',
            field=models.CharField(choices=[('PED', 'Pending'), ('PAI', 'Paid')], db_index=True, default='PED', help_text='This field signifies client payment status', max_length=15),
        ),
    ]
