# Generated by Django 5.1.2 on 2025-06-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0108_alter_billinglog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinglog',
            name='reason',
            field=models.CharField(choices=[('feedback_submitted', 'Feedback Submitted'), ('late_rescheduled', 'Late Rescheduled'), ('free_feedback', 'Initial Free Interviewer Feedback Submission for Client')], max_length=50),
        ),
    ]
