# Generated by Django 5.1.2 on 2025-06-03 11:44

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0110_alter_candidatetointerviewerfeedback_is_expired'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='intervieweravailability',
            managers=[
                ('object_all', django.db.models.manager.Manager()),
            ],
        ),
    ]
