# Generated by Django 5.1.2 on 2025-06-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0111_alter_intervieweravailability_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='reason_for_dropping',
            field=models.CharField(blank=True, choices=[('CNI', 'Candidate Not Interested'), ('CNA', 'Candidate Not Available'), ('CNR', 'Candidate Not Responded'), ('OTH', 'Others'), ('RJD', 'Rejected By HDIP'), ('NJ', 'Not Joined Candidate'), ('MSD', 'Multi Select Delete')], max_length=100, null=True),
        ),
    ]
