# Generated by Django 5.1.2 on 2025-06-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0112_alter_candidate_reason_for_dropping'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingrecord',
            name='total_amount_received_with_tax',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Total amount received for this month with tax. This field is automatically updated by the system.', max_digits=10),
        ),
        migrations.AddField(
            model_name='billingrecord',
            name='total_amount_received_without_tax',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Total amount received for this month without tax. This field is automatically updated by the system.', max_digits=10),
        ),
    ]
