# Generated by Django 5.1.2 on 2025-06-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0113_billingrecord_total_amount_received_with_tax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinglog',
            name='interviewer_payment_status',
            field=models.CharField(choices=[('PED', 'Pending'), ('PAI', 'Paid')], db_index=True, default='PED', help_text='This field signifies interveiwer payment status', max_length=15),
        ),
    ]
