# Generated by Django 5.1.2 on 2025-06-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0114_billinglog_interviewer_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinglog',
            name='is_interviewer_feedback_submitted_late',
            field=models.BooleanField(default=False, help_text='signifies the late feedback submission by interviewer'),
        ),
        migrations.AddField(
            model_name='billinglog',
            name='late_feedback_submission_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
