# Generated by Django 5.1.2 on 2025-06-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0115_billinglog_is_interviewer_feedback_submitted_late_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalclient',
            name='brand_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
