# Generated by Django 5.1.2 on 2025-06-15 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0116_internalclient_brand_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewfeedback',
            name='submitted_at',
            field=models.DateTimeField(blank=True, help_text='Signifying interviewer feedback submission', null=True),
        ),
    ]
