# Generated by Django 5.1.2 on 2025-06-24 10:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def migrate_job_round_data(apps, schema_editor):
    Job = apps.get_model("dashboard", "Job")
    JobInterviewRounds = apps.get_model("dashboard", "JobInterviewRounds")
    Candidate = apps.get_model("dashboard", "Candidate")
    Interview = apps.get_model("dashboard", "Interview")

    job_to_round_map = {}

    for job in Job.objects.all():
        # Create a single default round per job
        round = JobInterviewRounds.objects.create(
            job=job,
            name="Round 1",
            duration_minutes=60,
            sequence_number=1,
            other_details=job.other_details or {},
        )
        job_to_round_map[job.id] = round

    # Update last_completed_round for selected candidates
    valid_statuses = ["REC", "SNREC", "HREC", "NREC"]
    candidates = Candidate.objects.filter(
        status__in=valid_statuses, designation__isnull=False
    )

    for candidate in candidates:
        round = job_to_round_map.get(candidate.designation_id)
        if round:
            candidate.last_completed_round = round
            candidate.save()

    # Update job_round for completed interviews
    completed_statuses = ["REC", "SNREC", "HREC", "NREC", "NJ", "RESCH", "CSCH"]
    interviews = Interview.objects.filter(
        status__in=completed_statuses, candidate__designation__isnull=False
    )

    for interview in interviews:
        job = interview.candidate.designation
        round = job_to_round_map.get(job.id)
        if round:
            interview.job_round = round
            interview.save()


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0117_interviewfeedback_submitted_at"),
    ]

    operations = [
        # Create JobInterviewRounds model
        migrations.CreateModel(
            name="JobInterviewRounds",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived", models.BooleanField(default=False)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the round",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "duration_minutes",
                    models.IntegerField(
                        choices=[(60, "1 hour"), (90, "1.5 hours"), (120, "2 hours")],
                        default=60,
                        help_text="Interview duration",
                    ),
                ),
                (
                    "sequence_number",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="The order of this interview round within the job",
                    ),
                ),
                (
                    "other_details",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interview_rounds",
                        to="dashboard.job",
                    ),
                ),
            ],
        ),
        # Add new fields
        migrations.AddField(
            model_name="candidate",
            name="last_completed_round",
            field=models.ForeignKey(
                blank=True,
                help_text="The last round that the candidate has cleared",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="completed_candidates",
                to="dashboard.jobinterviewrounds",
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="next_round",
            field=models.ForeignKey(
                blank=True,
                help_text="The next interview round this candidate is supposed to attend",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="upcoming_candidates",
                to="dashboard.jobinterviewrounds",
            ),
        ),
        migrations.AddField(
            model_name="interview",
            name="job_round",
            field=models.ForeignKey(
                blank=True,
                help_text="The specific round of the job interview process to which this interview corresponds",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interviews",
                to="dashboard.jobinterviewrounds",
            ),
        ),
        # Custom logic to migrate job→round and update candidate/interview data
        migrations.RunPython(migrate_job_round_data),
        # Remove old fields first
        migrations.RemoveField(
            model_name="job",
            name="interview_time",
        ),
        migrations.RemoveField(
            model_name="job",
            name="other_details",
        ),
    ]
