# Generated by Django 5.1.2 on 2025-06-26 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0118_remove_job_interview_time_remove_job_other_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='interview_type',
            field=models.CharField(choices=[('AI', 'AI Interview'), ('P2P', 'Peer to Peer Interview')], default='P2P', max_length=15),
        ),
    ]
